import type { CertificationModel } from "./types";

export const certificationCatalog: CertificationModel[] = [
  {
    id: "comptia-security-plus",
    provider: "CompTIA",
    title: "Security+",
    description: "Foundational cybersecurity certification placeholder.",
    subjectIds: ["cybersecurity"],
    recommendedConceptIds: ["identity-verification", "authentication-factors", "role-based-access-control"],
    recommendedSkillIds: ["explain-identity-proofing", "classify-auth-factors", "design-rbac"],
    estimatedPrepTime: "8-12 weeks",
  },
  {
    id: "aws-cloud-practitioner",
    provider: "AWS",
    title: "Cloud Practitioner",
    description: "Cloud fundamentals certification placeholder.",
    subjectIds: ["programming", "business"],
    recommendedConceptIds: ["identity-verification"],
    recommendedSkillIds: ["classify-auth-factors"],
    estimatedPrepTime: "4-6 weeks",
  },
  {
    id: "cisco-ccna",
    provider: "Cisco",
    title: "CCNA",
    description: "Networking certification placeholder.",
    subjectIds: ["cybersecurity", "engineering"],
    recommendedConceptIds: ["authentication-factors"],
    recommendedSkillIds: ["classify-auth-factors"],
    estimatedPrepTime: "10-16 weeks",
  },
  {
    id: "microsoft-azure-fundamentals",
    provider: "Microsoft",
    title: "Azure Fundamentals",
    description: "Microsoft cloud fundamentals placeholder.",
    subjectIds: ["programming", "business"],
    recommendedConceptIds: ["identity-verification"],
    recommendedSkillIds: ["explain-identity-proofing"],
    estimatedPrepTime: "4-6 weeks",
  },
  {
    id: "pmi-capm",
    provider: "PMI",
    title: "CAPM",
    description: "Project management certification placeholder.",
    subjectIds: ["business"],
    recommendedConceptIds: [],
    recommendedSkillIds: [],
    estimatedPrepTime: "8-10 weeks",
  },
  {
    id: "faa-drone-placeholder",
    provider: "FAA",
    title: "Remote Pilot Certificate",
    description: "Aviation certification placeholder.",
    subjectIds: ["engineering"],
    recommendedConceptIds: [],
    recommendedSkillIds: [],
    estimatedPrepTime: "3-5 weeks",
  },
  {
    id: "medical-assistant-placeholder",
    provider: "Medical",
    title: "Medical Assistant Foundations",
    description: "Medical certification placeholder.",
    subjectIds: ["healthcare"],
    recommendedConceptIds: [],
    recommendedSkillIds: [],
    estimatedPrepTime: "12-20 weeks",
  },
  {
    id: "trades-safety-placeholder",
    provider: "Trades",
    title: "Trade Safety Foundations",
    description: "Trade competency placeholder.",
    subjectIds: ["trades", "woodworking"],
    recommendedConceptIds: [],
    recommendedSkillIds: [],
    estimatedPrepTime: "2-4 weeks",
  },
  {
    id: "finance-literacy-placeholder",
    provider: "Finance",
    title: "Financial Literacy Foundations",
    description: "Finance education credential placeholder.",
    subjectIds: ["finance"],
    recommendedConceptIds: [],
    recommendedSkillIds: [],
    estimatedPrepTime: "4-8 weeks",
  },
  {
    id: "other-portfolio-placeholder",
    provider: "Others",
    title: "Portfolio Credential",
    description: "General credential placeholder.",
    subjectIds: ["art", "music", "languages"],
    recommendedConceptIds: [],
    recommendedSkillIds: [],
    estimatedPrepTime: "Flexible",
  },
];

export function findCertification(certificationId: string) {
  return certificationCatalog.find((certification) => certification.id === certificationId);
}
