import type { CurriculumConceptLibraryItem } from "./types";

export const curriculumConceptLibrary: CurriculumConceptLibraryItem[] = [
  {
    id: "identity-verification",
    title: "Identity Verification",
    description: "Confirming that a person or system is who they claim to be.",
    difficulty: "Beginner",
    prerequisiteIds: [],
    dependentConceptIds: ["authentication-factors", "role-based-access-control"],
    estimatedMasteryTime: "2 hours",
    examplesPlaceholder: ["Badge check", "Account proofing", "Identity document review"],
    commonMistakes: ["Confusing identity proofing with authorization"],
    relatedConceptIds: ["authentication-factors"],
  },
  {
    id: "authentication-factors",
    title: "Authentication Factors",
    description: "Knowledge, possession, inherence, location, and behavior signals.",
    difficulty: "Beginner",
    prerequisiteIds: ["identity-verification"],
    dependentConceptIds: ["role-based-access-control"],
    estimatedMasteryTime: "3 hours",
    examplesPlaceholder: ["Password", "Hardware token", "Fingerprint"],
    commonMistakes: ["Treating two passwords as two factors"],
    relatedConceptIds: ["identity-verification", "role-based-access-control"],
  },
  {
    id: "role-based-access-control",
    title: "Role-Based Access Control",
    description: "Assigning permissions through roles that match responsibilities.",
    difficulty: "Intermediate",
    prerequisiteIds: ["identity-verification", "authentication-factors"],
    dependentConceptIds: ["least-privilege"],
    estimatedMasteryTime: "4 hours",
    examplesPlaceholder: ["Help desk role", "Finance approver role"],
    commonMistakes: ["Assigning direct permissions to every user"],
    relatedConceptIds: ["least-privilege"],
  },
  {
    id: "least-privilege",
    title: "Least Privilege",
    description: "Granting only the access required to complete the work.",
    difficulty: "Intermediate",
    prerequisiteIds: ["role-based-access-control"],
    dependentConceptIds: [],
    estimatedMasteryTime: "3 hours",
    examplesPlaceholder: ["Temporary elevated access", "Read-only reporting"],
    commonMistakes: ["Leaving emergency access permanently enabled"],
    relatedConceptIds: ["role-based-access-control"],
  },
  {
    id: "linear-equations",
    title: "Linear Equations",
    description: "Solving equations where variables have a first-degree relationship.",
    difficulty: "Beginner",
    prerequisiteIds: [],
    dependentConceptIds: ["quadratic-equations"],
    estimatedMasteryTime: "5 hours",
    examplesPlaceholder: ["2x + 4 = 12", "y = mx + b"],
    commonMistakes: ["Forgetting inverse operations"],
    relatedConceptIds: ["quadratic-equations"],
  },
  {
    id: "quadratic-equations",
    title: "Quadratic Equations",
    description: "Working with second-degree equations and factor patterns.",
    difficulty: "Intermediate",
    prerequisiteIds: ["linear-equations"],
    dependentConceptIds: ["functions"],
    estimatedMasteryTime: "8 hours",
    examplesPlaceholder: ["x^2 + 5x + 6 = 0"],
    commonMistakes: ["Dropping negative signs while factoring"],
    relatedConceptIds: ["linear-equations", "functions"],
  },
];

export function findCurriculumConcept(conceptId: string) {
  return curriculumConceptLibrary.find((concept) => concept.id === conceptId);
}
