import type { GlobalSubject, LearningSubject } from "./types";

export const globalSubjectCatalog: GlobalSubject[] = [
  {
    id: "mathematics",
    name: "Mathematics",
    description: "Number sense, algebra, geometry, statistics, and calculus.",
    iconPlaceholder: "math-icon",
    color: "#38bdf8",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 220,
    relatedSubjectIds: ["science", "engineering", "finance"],
  },
  {
    id: "science",
    name: "Science",
    description: "Natural sciences, experiments, and applied reasoning.",
    iconPlaceholder: "science-icon",
    color: "#22c55e",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 180,
    relatedSubjectIds: ["mathematics", "healthcare", "engineering"],
  },
  {
    id: "history",
    name: "History",
    description: "People, events, geography, and historical thinking.",
    iconPlaceholder: "history-icon",
    color: "#f59e0b",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 140,
    relatedSubjectIds: ["language-arts", "business"],
  },
  {
    id: "language-arts",
    name: "Language Arts",
    description: "Reading, writing, rhetoric, and communication.",
    iconPlaceholder: "language-arts-icon",
    color: "#f472b6",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 160,
    relatedSubjectIds: ["history", "business", "languages"],
  },
  {
    id: "programming",
    name: "Programming",
    description: "Software, computational thinking, and project development.",
    iconPlaceholder: "programming-icon",
    color: "#a78bfa",
    difficultyRange: "Beginner to Professional",
    estimatedLearningHours: 260,
    relatedSubjectIds: ["cybersecurity", "engineering", "business"],
  },
  {
    id: "cybersecurity",
    name: "Cybersecurity",
    description: "Security concepts, risk, identity, networks, and defense.",
    iconPlaceholder: "security-icon",
    color: "#818cf8",
    difficultyRange: "Beginner to Professional",
    estimatedLearningHours: 240,
    relatedSubjectIds: ["programming", "business", "engineering"],
  },
  {
    id: "finance",
    name: "Finance",
    description: "Financial literacy, accounting basics, investing, and planning.",
    iconPlaceholder: "finance-icon",
    color: "#22c55e",
    difficultyRange: "Beginner to Professional",
    estimatedLearningHours: 150,
    relatedSubjectIds: ["mathematics", "business", "life-skills"],
  },
  {
    id: "business",
    name: "Business",
    description: "Operations, management, entrepreneurship, and strategy.",
    iconPlaceholder: "business-icon",
    color: "#fb923c",
    difficultyRange: "Beginner to Professional",
    estimatedLearningHours: 180,
    relatedSubjectIds: ["finance", "language-arts", "programming"],
  },
  {
    id: "trades",
    name: "Trades",
    description: "Applied hands-on professional trade skills.",
    iconPlaceholder: "trades-icon",
    color: "#facc15",
    difficultyRange: "Beginner to Journeyman",
    estimatedLearningHours: 300,
    relatedSubjectIds: ["woodworking", "automotive", "engineering"],
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Design, systems, mechanics, electronics, and problem solving.",
    iconPlaceholder: "engineering-icon",
    color: "#22d3ee",
    difficultyRange: "Intermediate to Professional",
    estimatedLearningHours: 320,
    relatedSubjectIds: ["mathematics", "science", "programming"],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    description: "Health science, care skills, terminology, and patient safety.",
    iconPlaceholder: "healthcare-icon",
    color: "#dc2626",
    difficultyRange: "Beginner to Professional",
    estimatedLearningHours: 260,
    relatedSubjectIds: ["science", "life-skills"],
  },
  {
    id: "music",
    name: "Music",
    description: "Music theory, performance, practice, and ear training.",
    iconPlaceholder: "music-icon",
    color: "#c084fc",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 200,
    relatedSubjectIds: ["art", "languages"],
  },
  {
    id: "art",
    name: "Art",
    description: "Visual creation, design fundamentals, and creative practice.",
    iconPlaceholder: "art-icon",
    color: "#fb7185",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 180,
    relatedSubjectIds: ["music", "business"],
  },
  {
    id: "languages",
    name: "Languages",
    description: "Vocabulary, grammar, listening, speaking, and culture.",
    iconPlaceholder: "languages-icon",
    color: "#14b8a6",
    difficultyRange: "Beginner to Fluent",
    estimatedLearningHours: 300,
    relatedSubjectIds: ["language-arts", "history"],
  },
  {
    id: "woodworking",
    name: "Woodworking",
    description: "Tool safety, joinery, materials, and project craft.",
    iconPlaceholder: "woodworking-icon",
    color: "#d97706",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 180,
    relatedSubjectIds: ["trades", "art", "engineering"],
  },
  {
    id: "automotive",
    name: "Automotive",
    description: "Vehicle systems, diagnostics, safety, and maintenance.",
    iconPlaceholder: "automotive-icon",
    color: "#94a3b8",
    difficultyRange: "Beginner to Professional",
    estimatedLearningHours: 260,
    relatedSubjectIds: ["trades", "engineering"],
  },
  {
    id: "life-skills",
    name: "Life Skills",
    description: "Practical skills for daily life, planning, and resilience.",
    iconPlaceholder: "life-skills-icon",
    color: "#38bdf8",
    difficultyRange: "Beginner to Advanced",
    estimatedLearningHours: 120,
    relatedSubjectIds: ["finance", "healthcare", "business"],
  },
];

export const learningSubjects: LearningSubject[] = [
  {
    id: "math",
    title: "Math",
    description: "Algebra, geometry, statistics, and calculus foundations.",
    topics: [
      {
        id: "algebra",
        title: "Algebra",
        childTopics: [
          { id: "linear-equations", title: "Linear Equations" },
          { id: "quadratic-equations", title: "Quadratic Equations" },
        ],
      },
      { id: "calculus", title: "Calculus" },
    ],
  },
  {
    id: "science",
    title: "Science",
    description: "Core science concepts, labs, and reference materials.",
    topics: [{ id: "biology", title: "Biology" }, { id: "physics", title: "Physics" }],
  },
  {
    id: "history",
    title: "History",
    description: "Historical periods, timelines, primary sources, and review notes.",
    topics: [{ id: "world-history", title: "World History" }],
  },
  {
    id: "language-arts",
    title: "Language Arts",
    description: "Reading, writing, vocabulary, and discussion practice.",
    topics: [{ id: "writing", title: "Writing" }],
  },
  {
    id: "programming",
    title: "Programming",
    description: "Software fundamentals, coding practice, and project work.",
    topics: [{ id: "javascript", title: "JavaScript" }],
  },
  {
    id: "cybersecurity",
    title: "Cybersecurity",
    description: "Security concepts, certification prep, labs, and practice exams.",
    topics: [
      {
        id: "security-plus",
        title: "Security+",
        childTopics: [
          { id: "authentication", title: "Authentication" },
          { id: "access-control", title: "Access Control" },
        ],
      },
    ],
  },
  {
    id: "finance",
    title: "Finance",
    description: "Financial literacy and personal money education.",
    topics: [{ id: "budgeting", title: "Budgeting" }],
  },
  {
    id: "trades",
    title: "Trades",
    description: "Hands-on trade skills and shop practice.",
    topics: [{ id: "woodworking", title: "Woodworking" }],
  },
  {
    id: "languages",
    title: "Languages",
    description: "Language learning, vocabulary, speaking, and listening practice.",
    topics: [{ id: "spanish", title: "Spanish" }],
  },
  {
    id: "business",
    title: "Business",
    description: "Operations, management, entrepreneurship, and planning.",
    topics: [{ id: "operations", title: "Operations" }],
  },
  {
    id: "health",
    title: "Health",
    description: "Wellness education, anatomy, nutrition, and health literacy.",
    topics: [{ id: "wellness", title: "Wellness" }],
  },
  {
    id: "hobbies",
    title: "Hobbies",
    description: "Creative and recreational learning paths.",
    topics: [{ id: "music", title: "Music" }],
  },
];

export function findLearningSubject(subjectId: string) {
  return learningSubjects.find((subject) => subject.id === subjectId);
}
