import assert from 'node:assert/strict';
import test from 'node:test';
import { readFileSync } from 'node:fs';
import { transpileModule, ModuleKind, ScriptTarget } from 'typescript';
import * as shared from '../src/lib/atlas/shared';
const id='12345678-1234-4234-8234-123456789012';
const owner='owner';
function load(path:string,modules:Record<string,unknown>){const m={exports:{} as Record<string,Function>};const code=transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ModuleKind.CommonJS,target:ScriptTarget.ES2020}}).outputText;new Function('require','module','exports',code)((name:string)=>{if(name in modules)return modules[name];return require(name);},m,m.exports);return m.exports;}
function fixture(options:{member?:boolean;denyQuota?:boolean;failRecord?:boolean;providerFail?:boolean}={}){
 const tables:Record<string,Array<Record<string,unknown>>>={profiles:[{id:owner,role:options.member?'member':'admin'}],atlas_records:[],atlas_turns:[],atlas_devices:[],atlas_usage:[],beast_admin_staff_observation_runs:[]};let calls=0;
 const db={rpc:async()=>({data:!options.denyQuota,error:null}),from(table:string){let op='select',value:Record<string,unknown>={},single=false;let fields='*';const filters:Array<(r:Record<string,unknown>)=>boolean>=[];const q={select(f='*'){fields=f;return q;},eq(k:string,v:unknown){filters.push(r=>r[k]===v);return q;},is(k:string,v:unknown){filters.push(r=>(r[k]??null)===v);return q;},gt(k:string,v:unknown){filters.push(r=>String(r[k])>String(v));return q;},order(){return q;},limit(){return q;},maybeSingle(){single=true;return q;},single(){single=true;return q;},insert(v:Record<string,unknown>){op='insert';value=v;return q;},update(v:Record<string,unknown>){op='update';value=v;return q;},then(resolve:(v:unknown)=>unknown){const rows=tables[table]||[];let found=rows.filter(r=>filters.every(f=>f(r)));if(op==='insert'){if(options.failRecord&&table==='atlas_records')return Promise.resolve({data:null,error:'failed'}).then(resolve);const row={id,created_at:new Date().toISOString(),status:'queued',...value};if(rows.some(r=>r.id===row.id))return Promise.resolve({data:null,error:'duplicate'}).then(resolve);rows.push(row);found=[row];}if(op==='update')found.forEach(r=>Object.assign(r,value));const projected=found.map(r=>fields==='*'?{...r}:Object.fromEntries(fields.split(',').map(k=>[k,r[k]])));return Promise.resolve({data:single?projected[0]||null:projected,error:null}).then(resolve);}};return q;}};
 const server=load('src/lib/atlas/server.ts',{'@/lib/supabase/admin':{createAdminClient:()=>db},'@/lib/supabase/server':{createRouteClient:()=>({...db,auth:{getUser:async()=>({data:{user:{id:owner}},error:null})}})},'./shared':shared,'./connections':{inspectAtlasConnections:async()=>({access:'read-only'}),atlasConnectionSummary:()=> 'Read-only connections checked.'},'@/lib/digitalStaffRuntime/provider':{requestOpenAIResponse:async()=>{calls++;if(options.providerFail)throw new Error('sensitive provider detail');return {output:[{type:'message',content:[{type:'output_text',text:'Here is your dated rundown.'}]}]};}}});
 return {server,tables,calls:()=>calls,seed:(question:string)=>tables.atlas_turns.push({id,owner_id:owner,question,status:'queued',created_at:new Date().toISOString()})};
}
test('ATLAS explicit save parser never mistakes a general discussion for a save',()=>{assert.equal(shared.directAtlasAction('Can you remember things?'),null);assert.equal(shared.directAtlasAction('Please explain how to add a task'),null);assert.deepEqual(shared.directAtlasAction('Remember that Army comes first'),{kind:'memory',body:'Army comes first'});assert.deepEqual(shared.directAtlasAction('Add task: Connect Instagram'),{kind:'task',body:'Connect Instagram'});assert.throws(()=>shared.atlasText('x'.repeat(4001)));assert.equal(shared.isAtlasId('../records'),false);});
test('ATLAS browser mutations reject foreign and missing Origin',async()=>{const f=fixture();for(const origin of ['', 'https://evil.example'])assert.equal(await f.server.atlasAuth(new Request(shared.ATLAS_ORIGIN+'/api/atlas/turn',{method:'POST',headers:origin?{origin}:undefined})),null);assert.equal(await f.server.atlasAuth(new Request(shared.ATLAS_ORIGIN+'/api/atlas/turn',{method:'POST',headers:{origin:shared.ATLAS_ORIGIN}})),owner);});
test('ATLAS never grants access to a non-admin',async()=>{const f=fixture({member:true});assert.equal(await f.server.atlasAuth(new Request(shared.ATLAS_ORIGIN+'/api/atlas/state')),null);f.seed('Remember that no');await f.server.runAtlasTurn(id,owner);assert.equal(f.tables.atlas_records.length,0);});
test('ATLAS device key requires an unexpired, unrevoked hash and current admin role',async()=>{const f=fixture();const token='atlas_'+'a'.repeat(64);const req=new Request(shared.ATLAS_ORIGIN+'/api/atlas/state',{headers:{authorization:'Bearer '+token}});assert.equal(await f.server.atlasAuth(req),null);f.tables.atlas_devices.push({token_hash:f.server.hashAtlasToken(token),owner_id:owner,expires_at:'2099-01-01',revoked_at:null});assert.equal(await f.server.atlasAuth(req),owner);f.tables.atlas_devices[0].revoked_at='now';assert.equal(await f.server.atlasAuth(req),null);f.tables.atlas_devices[0].revoked_at=null;f.tables.atlas_devices[0].expires_at='2000-01-01';assert.equal(await f.server.atlasAuth(req),null);});
test('ATLAS device keys cannot pair new devices through cookie-only authorization',async()=>{const f=fixture();const req=new Request(shared.ATLAS_ORIGIN+'/api/atlas/pair',{method:'POST',headers:{authorization:'Bearer atlas_'+'a'.repeat(64)}});assert.equal(await f.server.atlasAuth(req,true),null);});
test('ATLAS records a receipt only after saving and concurrent workers save once',async()=>{const f=fixture();f.seed('Add task: Finish VIP STATUS');await Promise.all([f.server.runAtlasTurn(id,owner),f.server.runAtlasTurn(id,owner)]);assert.equal(f.tables.atlas_records.length,1);assert.equal(f.tables.atlas_records[0].owner_id,owner);assert.equal(f.tables.atlas_turns[0].status,'completed');assert.match(String(f.tables.atlas_turns[0].answer),/Saved to your ATLAS task list/);assert.equal(f.calls(),0);});
test('ATLAS failed writes cannot become claimed successes',async()=>{const f=fixture({failRecord:true});f.seed('Remember that this must not appear saved');await f.server.runAtlasTurn(id,owner);assert.equal(f.tables.atlas_records.length,0);assert.equal(f.tables.atlas_turns[0].status,'failed');assert.doesNotMatch(String(f.tables.atlas_turns[0].answer),/^Saved/);});
test('ATLAS cross-owner turn requests do not claim or execute a turn',async()=>{const f=fixture();f.seed('Remember that test');f.tables.atlas_turns[0].owner_id='someone-else';await f.server.runAtlasTurn(id,owner);assert.equal(f.tables.atlas_records.length,0);});
test('ATLAS quota failures fail closed',async()=>{const f=fixture({denyQuota:true});await assert.rejects(f.server.reserveAtlas(owner,'speech'),/Daily ATLAS limit/);});
test('ATLAS site checks use fixed HTTPS destinations and do not follow redirects',async()=>{const f=fixture();const urls:string[]=[];const result=await f.server.checkAtlasSites(async(url:string,init:RequestInit)=>{urls.push(url);assert.equal(init.redirect,'manual');return new Response(null,{status:302});});assert.deepEqual(urls,[...shared.atlasSites]);assert.equal(result.length,3);assert.equal(result[0].reachable,true);});
test('ATLAS provider output parser ignores tool and reasoning content',()=>{assert.equal(shared.atlasOutput({output:[{type:'reasoning',content:[{type:'output_text',text:'private'}]},{type:'message',content:[{type:'output_text',text:'hello'}]}]}),'hello');});
test('ATLAS provider failure is sanitized and never retried automatically',async()=>{const prev=process.env.OPENAI_API_KEY;process.env.OPENAI_API_KEY='fixture';try{const f=fixture({providerFail:true});f.seed('Give me my rundown');await f.server.runAtlasTurn(id,owner);await f.server.runAtlasTurn(id,owner);assert.equal(f.calls(),1);assert.equal(f.tables.atlas_turns[0].status,'failed');assert.doesNotMatch(String(f.tables.atlas_turns[0].answer),/sensitive provider/);}finally{if(prev===undefined)delete process.env.OPENAI_API_KEY;else process.env.OPENAI_API_KEY=prev;}});
test('ATLAS live connection checks do not call the language model',async()=>{const f=fixture();f.seed('Check my connections');await f.server.runAtlasTurn(id,owner);assert.equal(f.calls(),0);assert.equal(f.tables.atlas_turns[0].status,'completed');assert.match(String(f.tables.atlas_turns[0].answer),/Read-only/);});
test('ATLAS unavailable connection evidence never becomes healthy',async()=>{const c=load('src/lib/atlas/connections.ts',{'@/lib/server/beastAdminRepositoryProviders':{readGitHubRepositoryEvidence:async()=>{throw new Error('offline');},readVercelDeploymentEvidence:async()=>({provider:{status:'not_configured',detail:'Not configured'},observations:[]})},'@/lib/server/beastFusionReadModel':{loadBeastFusionCanonicalReadModel:async()=>({provider:{status:'stale'},canonical:null})}});const result=await c.inspectAtlasConnections();assert.equal(result.github.provider.status,'error');assert.equal(result.vercel.provider.status,'not_configured');assert.equal(result.beastFusion.provider.status,'stale');assert.equal(result.access,'read-only');assert.match(c.atlasConnectionSummary(result),/cannot edit code/);});
