import Image from "next/image";
import Link from "next/link";
import { digitalProfessionals } from "@/lib/digitalStaff";
import { getMemberSpecialistAssessment } from "@/lib/memberAgentCapabilityFramework";

const profiles = digitalProfessionals.flatMap((professional) => {
  const assessment = getMemberSpecialistAssessment(professional.canonicalId);
  return assessment ? [{ professional, assessment }] : [];
});

export default function MemberAISpecialistsPage() {
  return <main className="min-h-screen bg-[#0b1018] px-4 py-8 text-white sm:px-6 sm:py-12"><div className="mx-auto max-w-6xl space-y-8"><header className="rounded-3xl border border-indigo-300/20 bg-[#111827] p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.18em] text-indigo-200">Beast member AI</p><h1 className="mt-3 text-3xl font-black sm:text-5xl">Useful specialists. Auditable boundaries.</h1><p className="mt-4 max-w-4xl leading-7 text-slate-300">These profiles separate software generation, demonstrated capability, designed autonomy, actual authority, and permitted member data. Assessments are environment-bound self-assessments, not certification.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/ai-specialists/methodology" className="beast-button">How assessment works</Link><Link href="/release-notes" className="beast-button-secondary">Release notes</Link></div></header><section className="grid gap-5 md:grid-cols-2">{profiles.map(({ professional, assessment }) => <article key={professional.id} className="rounded-2xl border border-white/10 bg-[#111827] p-5"><div className="flex items-center gap-4"><Image src={professional.portrait.portrait_url || professional.portrait.placeholder_reference} alt={`Portrait of ${professional.name}`} width={72} height={72} className="h-[72px] w-[72px] rounded-2xl object-cover"/><div><p className="text-xs font-black uppercase tracking-wide text-indigo-200">{professional.team}</p><h2 className="mt-1 text-xl font-black">{professional.name}</h2><p className="text-sm font-bold text-amber-200">{professional.role}</p></div></div><p className="mt-4 text-sm leading-6 text-slate-300">{professional.mission}</p><dl className="mt-5 grid gap-3 border-t border-white/10 pt-4 text-sm"><div><dt className="text-xs font-black uppercase text-slate-500">Software</dt><dd className="mt-1 font-bold">{assessment.softwareGeneration}</dd></div><div><dt className="text-xs font-black uppercase text-slate-500">Designed autonomy</dt><dd className="mt-1 font-bold">Knight L{assessment.autonomy.level} · {assessment.autonomy.userRole}</dd></div><div><dt className="text-xs font-black uppercase text-slate-500">Authority</dt><dd className="mt-1 font-bold">{assessment.authority.classification}</dd></div></dl><Link href={`/ai-specialists/${professional.id}`} className="beast-button mt-5 inline-flex">View evidence and boundaries</Link></article>)}</section></div></main>;
}
