"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { DashboardCard, SectionHeader } from "@/app/components/design/DashboardPrimitives";
import { effectiveProposalQueueStatus, ownerProposalActions, proposalQueueStatuses, suppressDuplicateCanonicalProposals, type CanonicalStrategyProposal, type OwnerProposalAction, type ProposalQueueStatus } from "@/lib/ownerProposalReview";

type RecordedDecision = { action?: string; rationale?: string; detail?: string; decidedAt?: string; requestedAt?: string; governanceStatus?: string };
type DecisionRow = { id: string; execution_payload: { proposalId?: string; latestDecision?: RecordedDecision; decisionHistory?: RecordedDecision[] } | null };
const labels: Record<OwnerProposalAction, string> = { approve: "Approve", reject: "Reject", modify_return: "Modify / Return", watch: "Watch", investigate_further: "Investigate Further" };
const filterLabels: Record<ProposalQueueStatus, string> = { needs_decision: "Needs My Decision", investigating: "Investigating", approved: "Approved", watching: "Watching", rejected: "Rejected", completed: "Completed" };

export function StrategyProposalQueueWorkspace() {
  const [proposals, setProposals] = useState<CanonicalStrategyProposal[]>([]); const [decisions, setDecisions] = useState<DecisionRow[]>([]); const [filter, setFilter] = useState<ProposalQueueStatus>("needs_decision"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState<string | null>(null); const [drafts, setDrafts] = useState<Record<string, { rationale: string; detail: string }>>({});
  const load = useCallback(async () => { setLoading(true); setError(null); try { const response = await fetch("/api/admin/strategy-proposals", { cache: "no-store" }); const body = await response.json() as { error?: string; proposals?: CanonicalStrategyProposal[]; decisions?: DecisionRow[] }; if (!response.ok) throw new Error(body.error || "Proposal review is unavailable."); setProposals(suppressDuplicateCanonicalProposals(body.proposals || [])); setDecisions(body.decisions || []); } catch (reason) { setError(reason instanceof Error ? reason.message : "Proposal review is unavailable."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const latestActions = useMemo(() => new Map(decisions.flatMap((item) => item.execution_payload?.proposalId ? [[item.execution_payload.proposalId, item.execution_payload.latestDecision?.action]] as const : [])), [decisions]);
  const counts = useMemo(() => Object.fromEntries(proposalQueueStatuses.map((status) => [status, proposals.filter((proposal) => effectiveProposalQueueStatus(proposal, latestActions.get(proposal.id)) === status).length])) as Record<ProposalQueueStatus, number>, [latestActions, proposals]);
  const visible = useMemo(() => proposals.filter((proposal) => effectiveProposalQueueStatus(proposal, latestActions.get(proposal.id)) === filter), [filter, latestActions, proposals]);
  async function decide(proposal: CanonicalStrategyProposal, action: OwnerProposalAction) { const draft = drafts[proposal.id] || { rationale: "", detail: "" }; setBusy(`${proposal.id}:${action}`); setError(null); setNotice(null); try { const response = await fetch("/api/admin/strategy-proposals", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ proposalId: proposal.id, action, ...draft }) }); const body = await response.json() as { error?: string; warning?: string }; if (!response.ok) throw new Error(body.error || "Decision request failed."); setNotice(body.warning || "Decision retained for BeastFusion reconciliation."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Decision request failed."); } finally { setBusy(null); } }
  return <div className="space-y-6"><Link href="/dashboard/admin/development" className="text-sm font-bold text-amber-200">← Development Console</Link><DashboardCard accent="admin"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><SectionHeader eyebrow="Orchestrator 3.0 · Owner gate" title="Strategy proposal queue" description="Observer detects → Proposal Agent investigates and recommends → Owner decides → BeastFusion authorizes. Owner approval here never authorizes execution." /><div className="shrink-0 rounded-2xl border border-amber-300/30 bg-amber-300/10 px-5 py-4 text-center"><p className="text-3xl font-black text-white">{counts.needs_decision}</p><p className="text-xs font-black uppercase tracking-wider text-amber-200">Needs my decision</p></div></div></DashboardCard>
    {error ? <DashboardCard accent="admin"><p role="alert" className="text-sm text-red-200">{error}</p><button className="beast-button mt-4" onClick={() => void load()}>Retry</button></DashboardCard> : null}{notice ? <p role="status" className="rounded-xl border border-sky-300/20 bg-sky-300/5 p-4 text-sm text-sky-100">{notice}</p> : null}
    <nav aria-label="Proposal status filters" className="grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-6">{proposalQueueStatuses.map((status) => <button key={status} type="button" aria-pressed={filter === status} onClick={() => setFilter(status)} className={`min-h-14 rounded-xl border px-3 py-2 text-left text-sm font-black ${filter === status ? "border-amber-300/50 bg-amber-300/10 text-amber-100" : "border-white/10 text-slate-300"}`}><span className="block">{filterLabels[status]}</span><span className="mt-1 block text-xs text-slate-400">{counts[status]}</span></button>)}</nav>
    {loading ? <DashboardCard accent="admin"><p role="status" className="text-sm text-slate-300">Loading canonical proposals…</p></DashboardCard> : visible.length === 0 ? <DashboardCard accent="admin"><SectionHeader eyebrow={filterLabels[filter]} title="No proposals in this queue" description="Nothing is inferred from intake, agent messages, or legacy roadmap rows. Proposals appear only from canonical BeastFusion state." /></DashboardCard> : visible.map((proposal) => <ProposalCard key={proposal.id} proposal={proposal} decisions={decisions} draft={drafts[proposal.id] || { rationale: "", detail: "" }} busy={busy} setDraft={(draft) => setDrafts((current) => ({ ...current, [proposal.id]: draft }))} decide={decide} />)}</div>;
}

function ProposalCard({ proposal, decisions, draft, busy, setDraft, decide }: { proposal: CanonicalStrategyProposal; decisions: DecisionRow[]; draft: { rationale: string; detail: string }; busy: string | null; setDraft: (value: { rationale: string; detail: string }) => void; decide: (proposal: CanonicalStrategyProposal, action: OwnerProposalAction) => Promise<void> }) {
  const local = decisions.find((item) => item.execution_payload?.proposalId === proposal.id); const history: RecordedDecision[] = [...proposal.decisionHistory, ...(local?.execution_payload?.decisionHistory || [])]; const pendingAction = local?.execution_payload?.latestDecision?.action; const reviewable = proposal.status === "awaiting_owner_review" && !pendingAction; const effectiveStatus = effectiveProposalQueueStatus(proposal, pendingAction);
  return <DashboardCard accent="admin"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-black uppercase tracking-wider text-amber-200">{proposal.id} · {proposal.sourceAgent.replaceAll("_", " ")}</p><h2 className="mt-2 text-xl font-black text-white">{proposal.title}</h2><p className="mt-2 text-sm font-bold text-sky-100">Affected product: {proposal.product}</p></div><span className="h-fit rounded-full border border-white/15 px-3 py-1 text-xs font-bold text-slate-300">{filterLabels[effectiveStatus]}{pendingAction ? " · pending reconciliation" : ""}</span></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><TextBlock title="What was detected" text={proposal.detected} /><TextBlock title="Why it matters" text={proposal.whyItMatters} /><TextBlock title="Problem" text={proposal.problem} /><TextBlock title="Recommendation / verdict" text={proposal.recommendation} /></div>
    <dl className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{[["Confidence", proposal.confidence], ["Expected benefit", proposal.expectedBenefit], ["Estimated effort", proposal.effort], ["Risk", proposal.risk], ["Recommended priority", proposal.recommendedPriority]].map(([key, value]) => <div key={key} className="rounded-xl border border-white/10 p-4"><dt className="text-xs font-black uppercase text-slate-400">{key}</dt><dd className="mt-2 text-sm leading-6 text-white">{value}</dd></div>)}</dl>
    <section className="mt-4 rounded-xl border border-white/10 p-4"><h3 className="font-black text-white">Evidence and sources</h3><ul className="mt-3 space-y-3">{proposal.evidence.map((item, index) => <li key={`${item.source}:${index}`} className="text-sm text-slate-300"><span className="font-bold text-white">{item.summary}</span><span className="mt-1 block text-xs text-slate-400">Source: {item.source}{item.reference ? ` · ${item.reference}` : ""}{item.observedAt ? ` · ${item.observedAt}` : ""}</span></li>)}</ul></section>
    <div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><List title="Proposed scope" items={proposal.scope} /><List title="Exclusions" items={proposal.exclusions} /><List title="Dependencies" items={proposal.dependencies} /><List title="Success measures" items={proposal.successMeasures} /></div>
    {history.length ? <section className="mt-5 rounded-xl border border-sky-300/20 bg-sky-300/5 p-4"><h3 className="font-black text-sky-100">Decision history</h3><ol className="mt-3 space-y-3">{history.map((item, index) => <li key={`${item.decidedAt || item.requestedAt}:${index}`} className="text-sm text-sky-100"><span className="font-black">{item.action?.replaceAll("_", " ")}</span> — {item.rationale}{item.detail ? <span className="block text-xs text-sky-200">{item.detail}</span> : null}<span className="block text-xs text-slate-400">{item.decidedAt || item.requestedAt} · {item.governanceStatus} · non-executable</span></li>)}</ol></section> : null}
    {reviewable ? <div className="mt-5 grid gap-3"><label className="text-sm font-bold text-slate-200">Decision rationale<textarea className="beast-input mt-2 min-h-24 w-full" value={draft.rationale} onChange={(event) => setDraft({ ...draft, rationale: event.target.value })} /></label><label className="text-sm font-bold text-slate-200">Modification or investigation detail<textarea className="beast-input mt-2 min-h-24 w-full" value={draft.detail} onChange={(event) => setDraft({ ...draft, detail: event.target.value })} /></label><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-5">{ownerProposalActions.map((action) => <button key={action} type="button" disabled={Boolean(busy)} className={action === "approve" ? "beast-button min-h-11" : "min-h-11 rounded-lg border border-white/15 px-4 text-sm font-black text-white"} onClick={() => void decide(proposal, action)}>{busy === `${proposal.id}:${action}` ? "Recording…" : labels[action]}</button>)}</div></div> : null}<p className="mt-4 text-xs leading-5 text-slate-400">All decisions retain evidence and history as non-executable intake for canonical BeastFusion reconciliation. Approve ≠ execution authorization.</p></DashboardCard>;
}

function TextBlock({ title, text }: { title: string; text: string }) { return <section className="rounded-xl border border-white/10 p-4"><h3 className="text-xs font-black uppercase text-slate-400">{title}</h3><p className="mt-2 text-sm leading-6 text-white">{text}</p></section>; }
function List({ title, items }: { title: string; items: string[] }) { return <section className="rounded-xl border border-white/10 p-4"><h3 className="font-black text-white">{title}</h3>{items.length ? <ul className="mt-3 space-y-2 text-sm text-slate-300">{items.map((item) => <li key={item}>• {item}</li>)}</ul> : <p className="mt-3 text-sm text-slate-400">None recorded.</p>}</section>; }
