"use client";

import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { BeastMoneyShell } from "../BeastMoneyShell";
import { assessRetirementReadiness, compareRetirementTimelines, createRetirementTimeline, explainRetirementTimeline, type RetirementScenario, type RetirementValue } from "@/lib/retirementModel";

type Assumption = { label: string; value: string; source: string; confidence: string; reviewed: string; limitation: string };
const initial: Assumption[] = [
  { label: "Current age", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Required for an informational scenario." },
  { label: "Target retirement age", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Required for an informational scenario." },
  { label: "Planning life expectancy", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "A planning horizon, not a prediction." },
  { label: "Inflation assumption", value: "", source: "Default Assumption", confidence: "Low", reviewed: "Not reviewed", limitation: "Review and replace with your own planning assumption." },
  { label: "Pre-retirement growth assumption", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Informational only; not investment advice." },
  { label: "Post-retirement growth assumption", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Informational only; not investment advice." },
  { label: "Withdrawal assumption", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Used only as a displayed assumption, never a withdrawal recommendation." },
  { label: "Annual retirement expenses", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "An editable planning assumption, not a prediction." },
  { label: "Retirement account balance", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Enter a reviewed account balance." },
  { label: "Annual retirement contribution", value: "", source: "User Entered", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Enter a current contribution assumption." },
  { label: "Social Security estimate", value: "", source: "Official", confidence: "Unknown", reviewed: "Not reviewed", limitation: "Enter only a current official estimate; BeastMoney does not infer benefits." },
];

const modelKey: Record<string, string> = { "Current age":"currentAge", "Target retirement age":"targetAge", "Planning life expectancy":"lifeExpectancy", "Inflation assumption":"inflationRate", "Pre-retirement growth assumption":"preRetirementGrowthRate", "Post-retirement growth assumption":"postRetirementGrowthRate", "Withdrawal assumption":"safeWithdrawalRate", "Annual retirement expenses":"annualExpenses" };
const sourceFor = (source: string): RetirementValue["source"] => source === "Official" ? "user_entered_official" : source === "Imported" ? "imported" : source === "BeastMoney Estimated" ? "beastmoney_estimate" : source === "Default Assumption" ? "default_planning_assumption" : "user_entered_official";
function toScenario(assumptions: Assumption[]): RetirementScenario {
  const byLabel = new Map(assumptions.map((item) => [item.label, item]));
  const record = (label: string, key = modelKey[label] ?? label.toLowerCase().replaceAll(" ", "_")): RetirementValue => { const item = byLabel.get(label)!; const parsed = Number(item?.value); return { key, value: Number.isFinite(parsed) && parsed >= 0 ? parsed : undefined, source: sourceFor(item?.source ?? "User Entered"), asOf: item?.reviewed === "Not reviewed" ? "" : item?.reviewed ?? "", confidence: (item?.confidence?.toLowerCase() ?? "unknown") as RetirementValue["confidence"], assumptions: [item?.limitation ?? ""], limitations: [item?.limitation ?? ""] }; };
  return { currentAge:record("Current age"), targetAge:record("Target retirement age"), lifeExpectancy:record("Planning life expectancy"), inflationRate:record("Inflation assumption"), preRetirementGrowthRate:record("Pre-retirement growth assumption"), postRetirementGrowthRate:record("Post-retirement growth assumption"), safeWithdrawalRate:record("Withdrawal assumption"), annualExpenses:record("Annual retirement expenses"), retirementBalances:[record("Retirement account balance", "retirement_balance:account")], annualContributions:[record("Annual retirement contribution", "annual_contribution:account")], retirementIncome:[record("Social Security estimate", "official_social_security")] };
}

export default function RetirementAssumptionsPage() {
  const [assumptions, setAssumptions] = useState(initial);
  const [persistedAssumptions, setPersistedAssumptions] = useState<Assumption[] | null>(null);
  const [scenarioId, setScenarioId] = useState<string | null>(null);
  const [savedScenarios, setSavedScenarios] = useState<{ id: string; name: string; assumptions: Assumption[] }[]>([]);
  const [status, setStatus] = useState("Loading saved retirement assumptions…");
  const scenario = toScenario(persistedAssumptions ?? initial);
  const timeline = createRetirementTimeline(scenario);
  const readiness = assessRetirementReadiness(scenario);
  const explanation = explainRetirementTimeline(scenario, timeline);
  const comparisons = compareRetirementTimelines([{ id:scenarioId ?? "current", name:"Current scenario", scenario }, ...savedScenarios.filter((item) => item.id !== scenarioId).map((item) => ({ id:item.id, name:item.name, scenario:toScenario(item.assumptions) }))]);
  useEffect(() => { const load = async () => { try { const supabase = createClient(); const { data: user } = await supabase.auth.getUser(); if (!user.user) { setStatus("Sign in to save retirement assumptions."); return; } const { data, error } = await supabase.from("retirement_scenarios").select("id, name, assumptions").eq("owner_id", user.user.id).order("updated_at", { ascending:false }).limit(3); if (error) throw error; const records = (data ?? []).map((record) => ({ id:record.id, name:record.name, assumptions:(record.assumptions as Assumption[]) || initial })); setSavedScenarios(records); if (records[0]) { setScenarioId(records[0].id); setAssumptions(records[0].assumptions); setPersistedAssumptions(records[0].assumptions); setStatus("Loaded your saved assumptions."); } else setStatus("Review assumptions, then save your first scenario."); } catch { setStatus("Retirement assumptions could not be loaded. Check your connection and try again."); } }; void load(); }, []);
  const save = async () => { try { const supabase = createClient(); const { data: user } = await supabase.auth.getUser(); if (!user.user) throw new Error("Sign in required"); const payload = { owner_id: user.user.id, name: "Retirement plan", assumptions }; const query = scenarioId ? supabase.from("retirement_scenarios").update({ assumptions }).eq("id", scenarioId).eq("owner_id", user.user.id).select("id").single() : supabase.from("retirement_scenarios").insert(payload).select("id").single(); const { data, error } = await query; if (error) throw error; const persistedId = data?.id; const persistedScenario = toScenario(assumptions); const persistedTimeline = createRetirementTimeline(persistedScenario); if (persistedId) { setScenarioId(persistedId); setPersistedAssumptions(assumptions); if (persistedTimeline.years.length) { const { error: timelineError } = await supabase.from("retirement_timeline_runs").insert({ owner_id:user.user.id, scenario_id:persistedId, scenario_snapshot:persistedScenario, timeline:persistedTimeline, calculation_version:persistedTimeline.calculationVersion, reproducibility_key:persistedTimeline.reproducibilityKey }); if (timelineError) throw timelineError; } } setStatus("Saved. Your displayed timeline is a reproducible informational snapshot, not a guarantee."); } catch { setStatus("Save failed. No assumptions or timeline snapshot were changed."); } };
  return <BeastMoneyShell title="Retirement Assumptions" description="Review the inputs behind an informational retirement scenario.">
    <div className="space-y-5">
      <div className="beast-panel p-5 text-sm text-[#dbe3ef]"><strong>Informational only.</strong> Projections are not guarantees. BeastMoney does not tell you when to retire, claim benefits, withdraw funds, or change investments.</div>
      {assumptions.map((item, index) => <div key={item.label} className="beast-panel grid gap-3 p-5 md:grid-cols-2">
        <label className="grid gap-1"><span>{item.label}</span><input className="beast-input" value={item.value} onChange={(event) => setAssumptions(assumptions.map((entry, i) => i === index ? { ...entry, value: event.target.value } : entry))} placeholder="Enter a reviewed value" /></label>
        <div className="text-sm"><p><strong>Source:</strong> {item.source}</p><p><strong>Confidence:</strong> {item.confidence}</p><p><strong>Last reviewed:</strong> {item.reviewed}</p><p className="mt-2 text-[#aeb9c9]">{item.limitation}</p></div>
      </div>)}
      <button className="beast-button" onClick={save}>Save reviewed assumptions</button><p className="text-sm text-[#aeb9c9]">{status}</p>
      <section className="beast-panel space-y-4 p-5" aria-labelledby="retirement-timeline-heading">
        <div><h2 id="retirement-timeline-heading" className="text-xl font-bold text-white">Retirement income timeline</h2><p className="mt-1 text-sm text-[#aeb9c9]">Year-by-year informational income, expenses, and gap from your last successfully saved assumptions. Save edits to refresh this projection.</p></div>
        <p className="text-sm text-[#dbe3ef]"><strong>Confidence:</strong> {readiness.label === "documented" ? "Documented inputs" : "Incomplete inputs"}. {readiness.limitations[0]}</p>
        {timeline.years.length ? <div className="beast-table-wrap" tabIndex={0} role="region" aria-label="Retirement income timeline table"><table className="w-full min-w-[560px] text-left text-sm"><thead><tr className="border-b border-[#2a3242] text-[#aeb9c9]"><th className="p-2">Age</th><th className="p-2">Income</th><th className="p-2">Expenses</th><th className="p-2">Annual gap</th><th className="p-2">Cumulative gap</th></tr></thead><tbody>{timeline.years.map((year) => <tr key={year.age} className="border-b border-[#252c39]"><td className="p-2">{year.age}</td><td className="p-2">${year.incomeTotal.toLocaleString()}</td><td className="p-2">${year.expenses.toLocaleString()}</td><td className="p-2">${year.annualGap.toLocaleString()}</td><td className="p-2">${year.cumulativeGap.toLocaleString()}</td></tr>)}</tbody></table></div> : <div className="rounded-lg border border-[#2a3242] p-4 text-sm text-[#aeb9c9]">{timeline.warnings[0]}</div>}
        <details className="text-sm text-[#aeb9c9]"><summary className="cursor-pointer font-semibold text-white">How this is calculated</summary><p className="mt-2">{explanation.summary} {explanation.limitations.join(" ")}</p></details>
        <div className="flex flex-wrap gap-2"><button className="beast-button" onClick={() => window.print()}>Print retirement report</button><button className="beast-button" onClick={() => { const blob = new Blob([JSON.stringify({ scenario, timeline, readiness, explanation }, null, 2)], { type:"application/json" }); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = "beastmoney-retirement-report.json"; link.click(); URL.revokeObjectURL(href); }}>Export scenario JSON</button></div>
      </section>
      <section className="beast-panel space-y-3 p-5"><div><h2 className="text-xl font-bold text-white">Scenario comparison</h2><p className="text-sm text-[#aeb9c9]">Compare up to three of your saved scenarios using the same deterministic formula. This does not identify a best scenario or recommend a retirement date.</p></div>{comparisons.map((item) => <div key={item.id} className="rounded-lg border border-[#2a3242] p-3 text-sm text-[#dbe3ef]"><strong>{item.name}</strong><span className="ml-2 text-[#aeb9c9]">{item.timeline.years.length ? `Final cumulative gap: $${item.timeline.years.at(-1)?.cumulativeGap.toLocaleString()}` : "Incomplete assumptions"}</span></div>)}</section>
      <section className="beast-panel space-y-2 p-5 text-sm text-[#aeb9c9]"><h2 className="text-xl font-bold text-white">Planning education</h2><p><strong>Inflation:</strong> expenses use your displayed inflation assumption, so future amounts are not guaranteed.</p><p><strong>Income and gaps:</strong> each income source remains separate. A gap is arithmetic, not a recommendation to change benefits, investments, withdrawals, borrowing, or your retirement date.</p><p><strong>Confidence:</strong> source quality, review status, and missing information affect evidence quality—not the certainty of an outcome.</p></section>
      <div className="beast-panel p-5 text-sm text-[#aeb9c9]">Missing information lowers confidence. Official, imported, BeastMoney-estimated, and default values must remain distinct before any projection can be reviewed.</div>
    </div>
  </BeastMoneyShell>;
}
